name: Validate and Deploy Power Platform Solution

on:
  push:
    branches:
      - main

jobs:
  validate-inventory:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Unzip solution and locate bot.xml
        run: |
          unzip -o solutions/*.zip -d extracted/
          find extracted/ -name "bot.xml" -print

      - name: Extract agent ID (applicationId) from bot.xml
        id: extract_agent
        run: |
          BOT_XML_PATH=$(find extracted/ -name "bot.xml" | head -n 1)
          echo "Found bot.xml at: $BOT_XML_PATH"

          AGENT_ID=$(grep -oP '"applicationId"\s*:\s*"\K[^"]+' "$BOT_XML_PATH" || echo "NOT_FOUND")
          echo "Extracted agent ID: $AGENT_ID"

          echo "AGENT_ID=$AGENT_ID" >> $GITHUB_ENV

      - name: Call Inventory Validation Flow
        id: call_inventory
        env:
          FLOW_URL: ${{ secrets.INVENTORY_FLOW_URL }}
        run: |
          RESPONSE=$(curl -s -X POST "$FLOW_URL" \
            -H "Content-Type: application/json" \
            -d "{\"agentId\": \"$AGENT_ID\"}")

          echo "Inventory check response: $RESPONSE"
          EXISTS=$(echo $RESPONSE | jq -r '.exists')
          echo "EXISTS=$EXISTS" >> $GITHUB_ENV

      - name: Stop deployment if agent is unregistered
        if: env.EXISTS == 'false'
        run: |
          echo "Agent not found in inventory. Deployment halted until metadata is completed."
          exit 1

  deploy-solution:
    needs: validate-inventory
    runs-on: ubuntu-latest
    steps:
      - name: Deploy (Placeholder)
        run: echo "Would proceed to deployment step here"
